### ISSUE TITLE
question about input file.

### ISSUE THREAD

**Issue by ghost** [samiksome/C3D-weights#1]
hi. I ran feature_extraction.sh in C3D with your  prototxt file.
but I got below error:
I0715 04:46:29.560698 20473 layer_factory.hpp:77] Creating layer data
I0715 04:46:29.560792 20473 net.cpp:84] Creating Layer data
I0715 04:46:29.560823 20473 net.cpp:380] data -> data
I0715 04:46:29.560878 20473 net.cpp:380] data -> label
I0715 04:46:29.560933 20473 video_data_layer.cpp:67] Opening file youtube_frame.list
I0715 04:46:29.561043 20473 video_data_layer.cpp:137] Failed to read the clip list
I0715 04:46:29.561066 20473 video_data_layer.cpp:140] A total of 0 video chunks.
Segmentation fault (core dumped).
could you help me,please?

**Comment by samiksome92** [comment]
It seems you have set incorrect path for source file.
the full path is taken as root_folder+source.

**Comment by ghost** [comment]
no it's correct.

**Comment by samiksome92** [comment]
Then your source may not be in proper order. This error is thrown when it is unable to read the clip list properly

**Comment by ghost** [comment]
my source has been uploaded on:
https://ufile.io/of5gj

**Comment by samiksome92** [comment]
Yes from your source file I can see you have forgot to mention a category for every line.
Basically every line should be of the format:
`<path> <frame_num> <category>`

while extracting the category is not taken into account so you could simply put 0 for every one but it must be there, otherwise parsing fails.

Do refer to the C3D User Guide https://docs.google.com/document/d/1-QqZ3JHd76JfimY4QKqOojcEaf5g3JS0lNh-FHTxLag/edit for more information

**Comment by ghost** [comment]
Yes.
Thanks so much
